services:
    api:
        container_name: api
        image: node:25-alpine3.21
        working_dir: /app
        volumes:
            - ./:/app:Z
        command: sh -c "npm install && npm run dev"
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
        depends_on:
            - db
    db:
        container_name: db
        image: mariadb:latest
        environment:
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_PORT: ${MARIADB_PORT}
        ports:
            - '${MARIADB_PORT}:3306'
        volumes:
            - db_data:/var/lib/mysql:Z

volumes:
    db_data:
        driver: local

networks:
    default:
        name: gamingnet
